/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x07)
#define ID_MULTIEDIT_0    (GUI_ID_USER + 0x08)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 240, 240, 0, 0x64, 0 },
    { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 0, 0, 230, 220, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
#include <stdio.h>
#include "aux_data.h"
#include "lcd_spi2_drv.h"
WM_HWIN hItem;
//SD卡源数据路径！！
extern char src_dir[255];
//要拷贝到的FLASH路径
extern char dst_dir[255];
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)
    uint8_t ret ;

    // USER END
    switch (pMsg->MsgId)
    {
        case WM_INIT_DIALOG:
            //
            // Initialization of 'Framewin'
            //
            hItem = pMsg->hWin;
            FRAMEWIN_SetText(hItem, "BearPi Copy Ui Console");
            //
            // Initialization of 'Multiedit'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
            //MULTIEDIT_SetText(hItem, "Multiedit");
            MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_EDIT, GUI_BLACK);
            MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_EDIT, GUI_MAKE_COLOR(0x0000FF00));
            // USER START (Optionally insert additional code for further widget initialization)
            printf("开始拷贝文件:\n");
            ret = copy_ui_files(src_dir);

            if(ret != FR_OK)
            {
                MULTIEDIT_AddText(hItem, "Open SD card Fail!\n");
                MULTIEDIT_AddText(hItem, "Copy 0:==>1: Fail\n");
                MULTIEDIT_AddText(hItem, "View QSPI_FLASH UI Resource:\n");
								GUI_Delay(1000);
                LCD_Clear(BLACK);
                HAL_Delay(500);
                scan_files(dst_dir);
                LCD_Clear(BLACK);
                HAL_Delay(500);
                MULTIEDIT_AddText(hItem, "View Success!\n");
            }
            else
            {
                MULTIEDIT_AddText(hItem, "Open SD card Success\n");
                MULTIEDIT_AddText(hItem, "Copy 0:==>1: Success\n");
                GUI_Delay(100);
            }
            // USER END
            break;

        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;

            switch(Id)
            {
                case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
                    switch(NCode)
                    {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;

                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;

                        case WM_NOTIFICATION_VALUE_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                            // USER START (Optionally insert additional code for further notification handling)
                            // USER END
                    }

                    break;
                    // USER START (Optionally insert additional code for further Ids)
                    // USER END
            }

            break;

        // USER START (Optionally insert additional message handling)
        // USER END
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
